### ISSUE TITLE
Why isn't this available in repo?

### ISSUE THREAD

**Issue by ZAM-** [ace13/smart_proxy_dhcp_dnsmasq#10]
I can't find this or dns_dnsmasq smart proxy plugins available from the foreman-plugins yum repo for Foreman version 1.22. I'd prefer not to go down the path of manually installing.

**Comment by ekohl** [comment]
I submitted. https://github.com/theforeman/foreman-packaging/pull/3884 I'd appreciate it if someone could test this.

**Comment by ZAM-** [comment]
Any traction on this?

**Comment by ekohl** [comment]
I forgot to check if the build actually passed. It failed on the bundler file and that looks odd to me. https://github.com/theforeman/smart_proxy_dhcp_dnsmasq/pull/11 should fix it. I can do this in packaging but I think it's better to fix it in the gem itself.

**Comment by ekohl** [comment]
http://koji.katello.org/kojifiles/work/tasks/1344/211344/rubygem-smart_proxy_dhcp_dnsmasq-0.7-1.fm1_23.el7.src.rpm should work. Could you have a go and try it?

**Comment by ZAM-** [comment]
After rebuilding it, I was able to install the source RPM. I'm still having issues with finding free IPs though. I did see the foreman-proxy was able to successfully initialize the plugin.

**Comment by ananace** [comment]
The method of free IP finding changed since the 0.6 release of this plugin, I'm working on updating it to the new method at the moment.

**Comment by ekohl** [comment]
Should I cherry pick it into 1.22 or can we close this?

**Comment by ZAM-** [comment]
@ekohl I think this is working fine, but I haven't fully gotten my provisioning environment setup. I will report back if anything goes wrong. The RPM installed just fine. 

@ananace Do you recommend I use 0.5 of the dns_dnsmasq plugin?

**Comment by ananace** [comment]
@ZAM- I'd recommend using whichever the latest available version to you is.

If you run into any trouble, please open issues for it.
